services:
  app:
    build: .
    container_name: app
    working_dir: /var/www
    volumes:
      - ./backend:/var/www       # <-- use relative path to go up one folder
      - ./php.ini:/usr/local/etc/php/php.ini
    networks:
      - backend

  webserver:
    image: nginx:latest
    container_name: nginx_server
    ports:
      - "8100:80"
    volumes:
      - ./backend:/var/www       # <-- same here
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    networks:
      - backend

  db:
    image: mysql:8.0
    container_name: mysql_db
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: laravel
      MYSQL_USER: laravel
      MYSQL_PASSWORD: laravel
    networks:
      - backend

networks:
  backend:
    driver: bridge
